# Generated by Django 4.2.20 on 2026-02-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sitedata',
            name='site_id',
            field=models.CharField(max_length=6),
        ),
    ]
