# Generated by Django 4.2.20 on 2026-02-17 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_master_tasks_status_tasks_user_alter_tasks_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_info', to='tasks.country'),
            preserve_default=False,
        ),
    ]
