# Generated by Django 4.2.20 on 2026-02-17 10:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_tasks_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_tasks_country', to='tasks.country')),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='master_tasks',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='master_tasks_info', to='tasks.mastertasks'),
        ),
        migrations.DeleteModel(
            name='master_tasks',
        ),
    ]
