# Generated by Django 4.2.20 on 2026-02-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_mastertasks_alter_tasks_master_tasks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='country',
        ),
    ]
