# Generated by Django 4.2.20 on 2026-02-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_bulkupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkupload',
            name='title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
