# Generated by Django 4.2.20 on 2026-02-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_bulkupload_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulkupload',
            name='country',
        ),
        migrations.AddField(
            model_name='bulkupload',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
