# Generated by Django 5.2.11 on 2026-02-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_remove_bulkupload_country_bulkupload_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='retaier_selected_planogram',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
