# Generated by Django 5.2.11 on 2026-02-26 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_tasks_retaier_selected_planogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
